project:
  type: website
  output-dir: docs

website:
  title: "Process Modeling and Simulation"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Lectures
        menu:
          - href: lectures/lectures.qmd
            text: Lecture Overview
          - href: lectures/lecture-1/lecture-1.qmd
            text: Lecture 1
      - href: instructor.qmd
        text: Instructor

format:
  html:
    theme: cosmo
    toc: true
    page-layout: full